# Generated by Django 3.1 on 2020-08-17 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_loader', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HMMModel',
        ),
        migrations.DeleteModel(
            name='RegionModel',
        ),
    ]
